package com.redhat.vizuri.summit17;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String alert;
   private java.lang.String sound;

   public Message()
   {
   }

   public java.lang.String getAlert()
   {
      return this.alert;
   }

   public void setAlert(java.lang.String alert)
   {
      this.alert = alert;
   }

   public java.lang.String getSound()
   {
      return this.sound;
   }

   public void setSound(java.lang.String sound)
   {
      this.sound = sound;
   }

   public Message(java.lang.String alert, java.lang.String sound)
   {
      this.alert = alert;
      this.sound = sound;
   }

}