package com.redhat.vizuri.summit17;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PushNotification implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PushNotification() {
    }

}