package com.redhat.vizuri.summit17.processes;

import com.redhat.vizuri.demo.domain.Remediation;
import com.redhat.vizuri.demo.domain.Incident;
import com.redhat.vizuri.demo.domain.Status;

rule "High risk incident"
    agenda-group "assess-risk"
when 
    Incident( incidentType == "danger")
    $r: Remediation ( priority == null )
then
    modify($r) {
        setPriority(10)
    }
end

rule "Update remediation status"
    agenda-group "assess-risk"
when
    $r : Remediation( status == null )
then
    modify ($r) {
        setStatus(Status.REPORTED)
    }
end