package com.redhat.vizuri.summit17.processes;

import com.redhat.vizuri.demo.domain.Remediation;
import com.redhat.vizuri.demo.domain.Status;
import com.redhat.vizuri.demo.domain.Step;
import java.util.ArrayList;

rule "Assign remediation"
    agenda-group "assign-remediation"
when
    $r : Remediation ( workerId == null )
    // $w : Worker ( skill == $r.requiredSkill )
then
    modify ($r) {
        setWorkerId(99l);
    }
end

rule "Add steps"
    agenda-group "assign-remediation"
when
    $i : Incident ( )
    $r : Remediation ( incidentId == $i.id, steps == null )
    $steps : ArrayList ( )
        from collect ( Step ( incidentType == $i.incidentType ) )
then
    modify ($r) {
        setSteps($steps);
    }
end