import com.redhat.vizuri.demo.domain.Remediation;
import com.redhat.vizuri.demo.domain.Incident;
import com.redhat.vizuri.demo.domain.Step;

rule "High risk incident"
    agenda-group "assess-risk"
when
    Incident( incidentType in ("danger", "windshield"))
    $r: Remediation ( priority == null )
then
    modify($r) {
        setPriority(10)
    }
end

rule "Add steps"
    agenda-group "assess-risk"
    no-loop true
when
    $i : Incident ( )
    $r : Remediation ( incidentId == $i.id, steps == null )
    $steps : ArrayList ( size > 0 )
        from collect ( Step ( ) )
then
    modify ($r) {
        setSteps($steps);
    }
end
